{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the configMap volume to the volumes */}}
{{- define "nginx-config.configVolume" -}}
enabled: "true"
mountPath: "/etc/nginx/conf.d/default.conf"
subPath: "default.conf"
type: "custom"
volumeSpec:
  configMap:
    name: {{ include "common.names.fullname" . }}-config
{{- end -}}
{{- $_ := set .Values.persistence "nginx-config" (include "nginx-config.configVolume" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}