{{- $values := .Values.service.main.ports.http -}}
{{ $consul := .Values.consul}}
{{- if $consul.enabled -}}
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: {{ include "common.names.serviceAccountName" . }}
  labels: {{- include "common.labels" $ | nindent 4 }}
  annotations: {{- include "common.annotations" $ | nindent 4 }}
spec:
    protocol: {{ lower $values.protocol}}
{{- end }}

{{- include "common.all" . }}